//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _363.xbase
{
	using System;
	using System.Collections.Generic;

	public partial class Material
	{
		private string image;

		public string Name { get; set; }
		public string Type { get; set; }
		public string Image
		{
			get
			{
				if (image == null)
				{
					return "Images/picture.png";
				}
				return image;
			}
			set => image = value;
		}
		public decimal Price { get; set; }
		public int InStock { get; set; }
		public int MinCount { get; set; }
		public int InPack { get; set; }
		public string Unit { get; set; }

		public virtual MaterialType MaterialType { get; set; }
		public virtual Unit Unit1 { get; set; }
	}
}
